### ISSUE TITLE
Problems with team aliases

### ISSUE THREAD

**Issue by NilsIrl** [ctftime/ctftime.org#154]
For some reason the team [Pwn Intended](https://ctftime.org/team/120438) (which I am a member of), has multiple aliases that are the same thing:
![image](https://user-images.githubusercontent.com/26231126/84188022-d260f600-aa8a-11ea-8751-4d9c53c43411.png)

Trying to delete them doesn't work.

On the [RACTF](https://ctftime.org/event/1051) scoreboard, the aliases do not work and clicking on the team name returns error 500.

The team [PWN.rar](https://ctftime.org/team/121191) also seems to have the same scoreboard issue (although they don't have the multiple alias problem (suggesting that both of these issues may not be linked))

screenshot of aliases not working on the scoreboard:

![image](https://user-images.githubusercontent.com/26231126/84188936-51a2f980-aa8c-11ea-82ce-1697e77428b4.png)

Instead of "PWN to 0xE4" it should be "PWN.rar" and instead of "Pwnzorz" it should be "Pwn Intended".

**Comment by kyprizel** [comment]
Thanks, should be fixed now.

**Comment by lightspeedana** [comment]
Hi - I'm part of PWN.rar but we also have a problem in that our results from the past few CTFs do not show on our profile or add to our weight. 

<img width="1195" alt="Screenshot 2020-06-10 at 17 32 58" src="https://user-images.githubusercontent.com/17798041/84293999-73f64f00-ab40-11ea-853e-6dfc3af1e496.png">

RACTF:
<img width="1194" alt="Screenshot 2020-06-10 at 17 33 31" src="https://user-images.githubusercontent.com/17798041/84294050-83759800-ab40-11ea-91ed-fbe6ba228300.png">

And in HSCTF:
<img width="1183" alt="Screenshot 2020-06-10 at 17 34 03" src="https://user-images.githubusercontent.com/17798041/84294116-9d16df80-ab40-11ea-951a-b1013ab5cbfe.png">

We also would like to change our team name back to PWN to 0xE4 as the merge was unintended. Is there any way to fix these?

**Comment by NilsIrl** [comment]
I'm still having the problem as well. What seemed to have changed since last time:

* No more duplicate aliases
* Clicking on the aliased names on the RACTF scoreboard redirects to the correct team

(This applies to both PWN.rar and Pwn Intended)

**Comment by kyprizel** [comment]
`I'm still having the problem as well.`

What kind of problem do you still have?
Both scoreboards look fixed for me.

**Comment by NilsIrl** [comment]
It seems to be fixed now (for both teams), although it wasn't for some time (at least 4 hours ago).

Thank you for the help and sorry for creating more confusion than was needed.
